/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Koneksi;

/**
 *
 * @author PC
 */
public class ViewCariBarang extends javax.swing.JFrame {
    Koneksi Merlinda = new Koneksi();
    DefaultTableModel tabel = new DefaultTableModel();
    /**
     * Creates new form ViewCariBarang
     */
    public ViewCariBarang() {
        initComponents();
        setLocationRelativeTo(null);
        dataBarang();
    }
    
    private void dataBarang(){
        Merlinda.koneksiDatabase();
        
        tabel.addColumn("id Barang");
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Jenis Barang");
        tabel.addColumn("Jumlah Barang");
        
        JTableCari.setModel(tabel);
        try {
            String query = "SELECT * FROM tbl_barang";
            
            ResultSet ress = Merlinda.state.executeQuery(query);
            while (ress.next()){
                tabel.addRow(new Object[]{
                ress.getString("id"),
                ress.getString("nama"),
                ress.getString("jenis"),
                ress.getString("jumlah")
                });
            }
        } catch (Exception e) {
            System.err.println(""+e);
        }
    }
    
    public void cariBarang() {
        tabel.getDataVector().removeAllElements();
                
        try {
            Merlinda.koneksiDatabase();
            String queryCari = "SELECT * FROM tbl_barang where nama like '%"+JT_CariBarang.getText()+"%'";
            
            ResultSet ress = Merlinda.state.executeQuery(queryCari);
            
            while (ress.next()) {
                tabel.addRow(new Object[]{
                    ress.getString("id"), 
                    ress.getString("nama"),
                    ress.getString("jenis"),
                    ress.getString("jumlah")
                });
                JTableCari.setModel(tabel);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "eror tampil : " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JT_CariBarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableCari = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Cari Barang");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cari Barang :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        JT_CariBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JT_CariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JT_CariBarangKeyReleased(evt);
            }
        });
        getContentPane().add(JT_CariBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 250, -1));

        JTableCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTableCari);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 230));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 30, 290));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 350, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_CariBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JT_CariBarangKeyReleased
        // TODO add your handling code here:
        cariBarang();
    }//GEN-LAST:event_JT_CariBarangKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCariBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT_CariBarang;
    private javax.swing.JTable JTableCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
